// Mock Data for Demo Mode
// This file provides realistic Turkish data for development/demo purposes

import type {
  Bagis,
  IhtiyacSahibi,
  Kumbara,
  SosyalYardimBasvuru,
  Uye,
} from '@/types'

// ============================================
// MOCK MEMBERS
// ============================================
export const mockMembers: Uye[] = [
  {
    id: 'mem-001',
    tcKimlikNo: '12345678901',
    ad: 'Ahmet',
    soyad: 'Yılmaz',
    dogumTarihi: new Date('1985-03-15'),
    cinsiyet: 'erkek',
    telefon: '05321234567',
    email: 'ahmet.yilmaz@email.com',
    adres: {
      il: 'İstanbul',
      ilce: 'Kadıköy',
      mahalle: 'Moda',
      acikAdres: 'Moda Cad. No:15',
    },
    uyeTuru: 'aktif',
    uyeNo: 'KFD-2024-001',
    kayitTarihi: new Date('2024-01-15'),
    aidatDurumu: 'guncel',
    aidat: { tutar: 150 },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'mem-002',
    tcKimlikNo: '23456789012',
    ad: 'Fatma',
    soyad: 'Kaya',
    dogumTarihi: new Date('1990-07-22'),
    cinsiyet: 'kadin',
    telefon: '05339876543',
    email: 'fatma.kaya@email.com',
    adres: {
      il: 'İstanbul',
      ilce: 'Beşiktaş',
      mahalle: 'Levent',
      acikAdres: 'Levent Mah. Sok. No:8',
    },
    uyeTuru: 'aktif',
    uyeNo: 'KFD-2024-002',
    kayitTarihi: new Date('2024-02-10'),
    aidatDurumu: 'guncel',
    aidat: { tutar: 150 },
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'mem-003',
    tcKimlikNo: '34567890123',
    ad: 'Mehmet',
    soyad: 'Demir',
    dogumTarihi: new Date('1978-11-05'),
    cinsiyet: 'erkek',
    telefon: '05421112233',
    email: 'mehmet.demir@email.com',
    adres: {
      il: 'Ankara',
      ilce: 'Çankaya',
      mahalle: 'Kızılay',
      acikAdres: 'Atatürk Bulvarı No:42',
    },
    uyeTuru: 'onursal',
    uyeNo: 'KFD-2023-015',
    kayitTarihi: new Date('2023-06-20'),
    aidatDurumu: 'muaf',
    aidat: { tutar: 0 },
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2023-06-20'),
  },
  {
    id: 'mem-004',
    tcKimlikNo: '45678901234',
    ad: 'Ayşe',
    soyad: 'Öztürk',
    dogumTarihi: new Date('1995-04-18'),
    cinsiyet: 'kadin',
    telefon: '05554443322',
    email: 'ayse.ozturk@email.com',
    adres: {
      il: 'İzmir',
      ilce: 'Konak',
      mahalle: 'Alsancak',
      acikAdres: 'Kordon Boyu No:12',
    },
    uyeTuru: 'genc',
    uyeNo: 'KFD-2024-003',
    kayitTarihi: new Date('2024-03-05'),
    aidatDurumu: 'guncel',
    aidat: { tutar: 75 },
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'mem-005',
    tcKimlikNo: '56789012345',
    ad: 'Mustafa',
    soyad: 'Çelik',
    dogumTarihi: new Date('1982-09-30'),
    cinsiyet: 'erkek',
    telefon: '05066778899',
    email: 'mustafa.celik@email.com',
    adres: {
      il: 'Bursa',
      ilce: 'Nilüfer',
      mahalle: 'Fethiye',
      acikAdres: 'Fethiye Mah. No:25',
    },
    uyeTuru: 'aktif',
    uyeNo: 'KFD-2024-004',
    kayitTarihi: new Date('2024-04-12'),
    aidatDurumu: 'gecmis',
    aidat: { tutar: 150 },
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-04-12'),
  },
  {
    id: 'mem-006',
    tcKimlikNo: '67890123456',
    ad: 'Zeynep',
    soyad: 'Arslan',
    dogumTarihi: new Date('1988-12-25'),
    cinsiyet: 'kadin',
    telefon: '05377889900',
    email: 'zeynep.arslan@email.com',
    adres: {
      il: 'Antalya',
      ilce: 'Muratpaşa',
      mahalle: 'Lara',
      acikAdres: 'Lara Cad. No:55',
    },
    uyeTuru: 'destekci',
    uyeNo: 'KFD-2024-005',
    kayitTarihi: new Date('2024-05-01'),
    aidatDurumu: 'guncel',
    aidat: { tutar: 100 },
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-01'),
  },
]

// ============================================
// MOCK BENEFICIARIES
// ============================================
export const mockBeneficiaries: IhtiyacSahibi[] = [
  {
    id: 'ben-001',
    ad: 'Hasan',
    soyad: 'Yıldırım',
    tcKimlikNo: '11122233344',
    yabanciKimlikNo: '',
    tur: 'ihtiyac-sahibi-kisi',
    kategori: 'ihtiyac-sahibi-aile',
    dogumTarihi: new Date('1970-05-10'),
    cinsiyet: 'erkek',
    uyruk: 'Türkiye',
    cepTelefonu: '05301234567',
    cepTelefonuOperator: 'Turkcell',
    email: '',
    ulke: 'Türkiye',
    sehir: 'İstanbul',
    ilce: 'Sultangazi',
    mahalle: 'Esentepe',
    adres: 'Esentepe Mah. 234. Sok. No:5',
    dosyaNo: 'IS-2024-001',
    kayitTarihi: new Date('2024-01-10'),
    durum: 'aktif',
    ihtiyacDurumu: 'yuksek',
    basvuruSayisi: 3,
    yardimSayisi: 2,
    rizaBeyaniDurumu: 'alindi',
    toplamYardimTutari: 5000,
    aileHaneBilgileri: {
      medeniHal: 'evli',
      ailedekiKisiSayisi: 5,
      cocukSayisi: 3,
      yetimSayisi: 0,
      calısanSayisi: 0,
      bakmaklaYukumluSayisi: 4,
    },
    ekonomikSosyalDurum: {
      meslek: 'İşsiz',
      aylikGelir: 0,
      egitimDurumu: 'ilkokul',
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'ben-002',
    ad: 'Elif',
    soyad: 'Şahin',
    tcKimlikNo: '22233344455',
    yabanciKimlikNo: '',
    tur: 'ihtiyac-sahibi-kisi',
    kategori: 'yetim',
    dogumTarihi: new Date('2010-08-20'),
    cinsiyet: 'kadin',
    uyruk: 'Türkiye',
    cepTelefonu: '05449876543',
    cepTelefonuOperator: 'Vodafone',
    email: '',
    ulke: 'Türkiye',
    sehir: 'Ankara',
    ilce: 'Mamak',
    mahalle: 'Tuzluçayır',
    adres: 'Tuzluçayır Mah. 15. Cad. No:8',
    dosyaNo: 'AN-2024-002',
    kayitTarihi: new Date('2024-02-15'),
    durum: 'aktif',
    ihtiyacDurumu: 'orta',
    basvuruSayisi: 1,
    yardimSayisi: 1,
    rizaBeyaniDurumu: 'alindi',
    toplamYardimTutari: 2500,
    aileHaneBilgileri: {
      medeniHal: 'bekar',
      ailedekiKisiSayisi: 2,
      cocukSayisi: 0,
      yetimSayisi: 1,
      calısanSayisi: 1,
      bakmaklaYukumluSayisi: 0,
    },
    ekonomikSosyalDurum: {
      meslek: 'Öğrenci',
      aylikGelir: 1500,
      egitimDurumu: 'ortaokul',
    },
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'ben-003',
    ad: 'İbrahim',
    soyad: 'Koç',
    tcKimlikNo: '33344455566',
    yabanciKimlikNo: '',
    tur: 'ihtiyac-sahibi-kisi',
    kategori: 'engelli',
    dogumTarihi: new Date('1965-03-12'),
    cinsiyet: 'erkek',
    uyruk: 'Türkiye',
    cepTelefonu: '05551234567',
    cepTelefonuOperator: 'Türk Telekom',
    email: 'ibrahim.koc@email.com',
    ulke: 'Türkiye',
    sehir: 'İzmir',
    ilce: 'Bornova',
    mahalle: 'Altındağ',
    adres: 'Altındağ Mah. Çiçek Sok. No:12',
    dosyaNo: 'IZ-2024-003',
    kayitTarihi: new Date('2024-03-20'),
    durum: 'pasif',
    ihtiyacDurumu: 'dusuk',
    basvuruSayisi: 2,
    yardimSayisi: 2,
    rizaBeyaniDurumu: 'alindi',
    toplamYardimTutari: 8000,
    aileHaneBilgileri: {
      medeniHal: 'dul',
      ailedekiKisiSayisi: 1,
      cocukSayisi: 0,
      yetimSayisi: 0,
      calısanSayisi: 0,
      bakmaklaYukumluSayisi: 0,
    },
    ekonomikSosyalDurum: {
      meslek: 'Emekli',
      aylikGelir: 3500,
      egitimDurumu: 'lise',
    },
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-07-01'),
  },
]

// ============================================
// MOCK APPLICATIONS
// ============================================
export const mockApplications: SosyalYardimBasvuru[] = [
  {
    id: 'app-001',
    basvuranKisi: {
      ad: 'Hasan',
      soyad: 'Yıldırım',
      tcKimlikNo: '11122233344',
      telefon: '05301234567',
      adres: 'Esentepe Mah. 234. Sok. No:5',
    },
    yardimTuru: 'gida',
    talepEdilenTutar: 2000,
    gerekce: 'Aile geçim sıkıntısı yaşamaktadır. 3 çocuk okula gitmektedir.',
    belgeler: [],
    durum: 'beklemede',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'app-002',
    basvuranKisi: {
      ad: 'Elif',
      soyad: 'Şahin',
      tcKimlikNo: '22233344455',
      telefon: '05449876543',
      adres: 'Tuzluçayır Mah. 15. Cad. No:8',
    },
    yardimTuru: 'egitim',
    talepEdilenTutar: 3500,
    gerekce: 'Lise öğrencisi, okul masrafları karşılanamıyor.',
    belgeler: [],
    durum: 'onaylandi',
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'app-003',
    basvuranKisi: {
      ad: 'İbrahim',
      soyad: 'Koç',
      tcKimlikNo: '33344455566',
      telefon: '05551234567',
      adres: 'Altındağ Mah. Çiçek Sok. No:12',
    },
    yardimTuru: 'saglik',
    talepEdilenTutar: 5000,
    gerekce: 'İlaç ve tedavi masrafları karşılanamıyor.',
    belgeler: [],
    durum: 'beklemede',
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'app-004',
    basvuranKisi: {
      ad: 'Ayşe',
      soyad: 'Yılmaz',
      tcKimlikNo: '44455566677',
      telefon: '05367891234',
      adres: 'Kartal Mah. No:22',
    },
    yardimTuru: 'barinma',
    talepEdilenTutar: 4500,
    gerekce: 'Kira yardımı talebi, 2 ay gecikmiş kira borcu bulunmakta.',
    belgeler: [],
    durum: 'reddedildi',
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-25'),
  },
]

// ============================================
// MOCK KUMBARAS
// ============================================
export const mockKumbaras: Kumbara[] = [
  {
    id: 'kmb-001',
    kod: 'KMB-IST-001',
    ad: 'Kadıköy Merkez',
    konum: 'Kadıköy Merkez Camii',
    koordinat: undefined,
    qrKod: { kod: 'KMB-IST-001', tapilanTarih: new Date('2024-01-01') },
    sorumlu: {
      id: 'usr-001',
      name: 'Ali Veli',
      email: 'ali@kafkasder.org',
      phone: '05321111111',
      role: 'gorevli',
      isActive: true,
      permissions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    toplamTutar: 2500,
    toplamaBaşarina: 2500,
    toplamaGecmisi: [],
    durum: 'aktif',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'kmb-002',
    kod: 'KMB-ANK-001',
    ad: 'Kızılay Şube',
    konum: 'Kızılay AVM',
    koordinat: undefined,
    qrKod: { kod: 'KMB-ANK-001', tapilanTarih: new Date('2024-02-01') },
    sorumlu: {
      id: 'usr-002',
      name: 'Veli Kara',
      email: 'veli@kafkasder.org',
      phone: '05322222222',
      role: 'gorevli',
      isActive: true,
      permissions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    toplamTutar: 1800,
    toplamaBaşarina: 1800,
    toplamaGecmisi: [],
    durum: 'aktif',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'kmb-003',
    kod: 'KMB-IZM-001',
    ad: 'Alsancak Merkez',
    konum: 'Alsancak İskele',
    koordinat: undefined,
    qrKod: { kod: 'KMB-IZM-001', tapilanTarih: new Date('2024-03-01') },
    sorumlu: {
      id: 'usr-003',
      name: 'Selim Ak',
      email: 'selim@kafkasder.org',
      phone: '05323333333',
      role: 'gorevli',
      isActive: true,
      permissions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    toplamTutar: 3200,
    toplamaBaşarina: 3200,
    toplamaGecmisi: [],
    durum: 'pasif',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-05-20'),
  },
]

// ============================================
// MOCK DONATIONS
// ============================================
export const mockDonations: Bagis[] = [
  {
    id: 'don-001',
    bagisci: { id: 'mem-001', ad: 'Ahmet', soyad: 'Yılmaz' },
    tutar: 500,
    currency: 'TRY',
    amac: 'genel',
    odemeYontemi: 'kredi-karti',
    durum: 'tamamlandi',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'don-002',
    bagisci: { id: 'mem-002', ad: 'Fatma', soyad: 'Kaya' },
    tutar: 1000,
    currency: 'TRY',
    amac: 'egitim',
    odemeYontemi: 'havale',
    durum: 'tamamlandi',
    createdAt: new Date('2024-05-28'),
    updatedAt: new Date('2024-05-28'),
  },
  {
    id: 'don-003',
    bagisci: { id: 'ext-001', ad: 'Anonim', soyad: '' },
    tutar: 2500,
    currency: 'TRY',
    amac: 'saglik',
    odemeYontemi: 'nakit',
    durum: 'tamamlandi',
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-05-20'),
  },
]

// ============================================
// MOCK DASHBOARD STATS
// ============================================
export const mockDashboardStats = {
  activeMembers: mockMembers.length,
  totalBeneficiaries: mockBeneficiaries.length,
  totalDonations: mockDonations.reduce((sum, d) => sum + d.tutar, 0),
  activeKumbaras: mockKumbaras.filter((k) => k.durum === 'aktif').length,
  pendingApplications: mockApplications.filter((a) => a.durum === 'beklemede')
    .length,
  monthlyAid: 15500,
  donationsTrend: 12.5,
  monthlyDonations: [
    { month: 'Oca', amount: 45000 },
    { month: 'Şub', amount: 52000 },
    { month: 'Mar', amount: 48000 },
    { month: 'Nis', amount: 61000 },
    { month: 'May', amount: 55000 },
    { month: 'Haz', amount: 67000 },
  ],
  recentDonations: mockDonations.slice(0, 5),
  aidDistribution: [
    { name: 'Gıda', value: 35, color: '#14b8a6' },
    { name: 'Eğitim', value: 25, color: '#10b981' },
    { name: 'Sağlık', value: 20, color: '#0ea5e9' },
    { name: 'Barınma', value: 15, color: '#8b5cf6' },
    { name: 'Diğer', value: 5, color: '#64748b' },
  ],
}
