-- =============================================
-- MIGRATION: Add in_kind_aids table for ayni yardım
-- =============================================

CREATE TABLE IF NOT EXISTS public.in_kind_aids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id BIGINT NOT NULL REFERENCES public.beneficiaries(id) ON DELETE CASCADE,
  yardim_turu TEXT NOT NULL CHECK (yardim_turu IN ('gida', 'giyim', 'yakacak', 'diger')),
  miktar DECIMAL(10, 2) NOT NULL,
  birim TEXT NOT NULL CHECK (birim IN ('adet', 'kg', 'paket', 'kutu', 'takim', 'diger')),
  dagitim_tarihi DATE NOT NULL DEFAULT CURRENT_DATE,
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_in_kind_aids_beneficiary ON public.in_kind_aids(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_in_kind_aids_tarih ON public.in_kind_aids(dagitim_tarihi DESC);
CREATE INDEX IF NOT EXISTS idx_in_kind_aids_turu ON public.in_kind_aids(yardim_turu);

-- RLS
ALTER TABLE public.in_kind_aids ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view in_kind_aids" ON public.in_kind_aids
  FOR SELECT
  USING (true);

CREATE POLICY "Users can insert in_kind_aids" ON public.in_kind_aids
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Users can update in_kind_aids" ON public.in_kind_aids
  FOR UPDATE
  USING (true);

CREATE POLICY "Users can delete in_kind_aids" ON public.in_kind_aids
  FOR DELETE
  USING (true);

-- Update trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_in_kind_aids_updated_at
  BEFORE UPDATE ON public.in_kind_aids
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

